INSERT INTO `artists` (`id`, `firstname`, `lastname`)
VALUES (1, 'Daniel', 'Marcelin'),
       (2, 'Philippe', 'Laurent'),
       (3, 'Marius', 'Von Mayenburg'),
       (4, 'Olivier', 'Boudon'),
       (5, 'Anne Marie', 'Loop'),
       (6, 'Pietro', 'Varasso'),
       (7, 'Laurent', 'Caron'),
       (8, 'Élena', 'Perez'),
       (9, 'Guillaume', 'Alexandre'),
       (10, 'Claude', 'Semal'),
       (11, 'Laurence', 'Warin'),
       (12, 'Pierre', 'Wayburn'),
       (13, 'Gwendoline', 'Gauthier'),
       (14, 'Jacques', 'Brel'),
       (15, 'Salvatore', 'Adamo'),
       (16, 'Stromae', 'Cowboy'),
       (17, 'Angèle', 'Van Laeken'),
       (18, 'Arno', 'Hintjens'),
       (19, 'Alex', 'Callier'),
       (20, 'Wouter', 'De Backer'),
       (21, 'Jean', 'Dupont'),
       (22, 'Marie', 'Martin'),
       (23, 'Paul', 'Moreau'),
       (24, 'Sophie', 'Lefèvre'),
       (25, 'Antoine', 'Petit'),
       (26, 'Claire', 'Laurent'),
       (27, 'Nicolas', 'Roche'),
       (28, 'Émilie', 'Dubois'),
       (29, 'Guillaume', 'Durand'),
       (30, 'Camille', 'Leroy'),
       (31, 'Jan', 'De Vries'),
       (32, 'Piet', 'Janssen'),
       (33, 'Karel', 'De Bruin'),
       (34, 'Femke', 'Visser'),
       (35, 'Bram', 'Smit'),
       (36, 'Sanne', 'Bakker'),
       (37, 'Tom', 'Verhoeven'),
       (38, 'Lotte', 'De Wit'),
       (39, 'Daan', 'Van Dijk'),
       (40, 'Emma', 'De Lange'),
       (41, 'Michael', 'Smith'),
       (42, 'Jennifer', 'Johnson'),
       (43, 'William', 'Brown'),
       (44, 'Elizabeth', 'Davis'),
       (45, 'James', 'Wilson'),
       (46, 'Mary', 'Taylor'),
       (47, 'Robert', 'Anderson'),
       (48, 'Patricia', 'Thomas'),
       (49, 'David', 'Jackson'),
       (50, 'Linda', 'White'),
       (51, 'Martin', 'Robinson'),
       (52, 'Sophie', 'Edwards'),
       (53, 'Alexandre', 'Bernard'),
       (54, 'Chloé', 'Fontaine'),
       (55, 'Laurent', 'Marchand'),
       (56, 'Isabelle', 'Garnier'),
       (57, 'Sébastien', 'Girard'),
       (58, 'Manon', 'Petitjean'),
       (59, 'Olivier', 'Dupuis'),
       (60, 'Juliette', 'Renault'),
       (61, 'Hugo', 'Rousseau'),
       (62, 'Élise', 'Fontaine'),
       (63, 'Pascal', 'Martin'),
       (64, 'Claire', 'Fournier'),
       (65, 'Laurent', 'Morel'),
       (66, 'Amandine', 'Caron'),
       (67, 'Vincent', 'Lefèvre'),
       (68, 'Audrey', 'Mercier'),
       (69, 'Romain', 'Gauthier'),
       (70, 'Marine', 'Dupont'),
       (71, 'Dirk', 'Vermeer'),
       (72, 'Anke', 'Van den Berg'),
       (73, 'Tim', 'De Jong'),
       (74, 'Eva', 'De Graaf'),
       (75, 'Joost', 'De Ruiter'),
       (76, 'Lisa', 'Veenstra'),
       (77, 'Bas', 'Mulder'),
       (78, 'Marieke', 'De Klerk'),
       (79, 'Rik', 'Bos'),
       (80, 'Sander', 'De Vries'),
       (81, 'Oliver', 'Jones'),
       (82, 'Amelia', 'Harris'),
       (83, 'Benjamin', 'Thompson'),
       (84, 'Charlotte', 'Martin'),
       (85, 'Henry', 'Walker'),
       (86, 'Grace', 'Robinson'),
       (87, 'Samuel', 'Lewis'),
       (88, 'Victoria', 'Clark'),
       (89, 'Jack', 'Hall'),
       (90, 'Emily', 'Allen'),
       (91, 'Mathieu', 'Bernard'),
       (92, 'Fiona', 'Gallagher'),
       (93, 'Sophie', 'Rousseau'),
       (94, 'Leo', 'Gibson'),
       (95, 'Emma', 'Cooper'),
       (96, 'Liam', 'Carter'),
       (97, 'Zoe', 'Marshall'),
       (98, 'Mason', 'Scott'),
       (99, 'Ava', 'Peterson'),
       (100, 'Oliver', 'Wright');
